# -------------------------------------
# Minecraft Odyssey Config File
# -------------------------------------

# For most accessed configs
odyssey:
  require-resource-pack: true

# For mob related configs
mobs:
  enable-shiny-mobs: true
  enable-special-loot: true

# For world related configs
world:
  enable-obelisk-travel: true

# Server Based links
server-map:
  enabled: false
  name: "Vailcraft Map"
  link: "http://map.vailcraft.net:25563/#world:0:0:0:2250:0:0:0:0:perspective"