name: Odyssey
version: '${project.version}'
main: me.shadowalzazel.mcodyssey.Odyssey
api-version: '1.20'
authors: [ShadowAlzazel]
description: A server side expansion pack for a new minecraft adventure!

commands:
  summon_boss:
    description: "Summons an Odyssey boss."
    usage: /<command>
    permission: op
  enchant_gilded:
    description: "Applies the gilded enchantment to the current item in the main hand."
    usage: /<command>
    permission: op
  give_item:
    description: "Gives an Odyssey custom item."
    usage: /<command>
    permission: op
  place_feature_archaic_seed:
    description: "Places a custom feature"
    permission: default