name: $name
main: me.shadowalzazel.mcodyssey.Odyssey
version: $version
api-version: $apiVersion
authors: [ShadowAlzazel]
description: $description

commands:
  summon_boss:
    description: "Summons an Odyssey boss."
    usage: /<command>
    permission: op
  enchant_gilded:
    description: "Applies the gilded enchantment to the current item in the main hand."
    usage: /<command>
    permission: op
  give_item:
    description: "Gives an Odyssey custom item."
    usage: /<command>
    permission: op
  give_gilded_book:
    description: "Gives a Gilded Book with the enchantment."
    usage: /<command>
    permission: op
  give_spacerune_tablet:
    description: "Gives a Space Rune tablet."
    usage: /<command>
    permission: op
  place_feature_archaic_seed:
    description: "Places a custom feature"
    permission: default
  summon_mob:
    description: "Summons a Custom Mob."
    usage: /<command>
    permission: op
  summon_doppelganger:
    description: "Summons a Doppelganger."
    usage: /<command>
    permission: op