name: Odyssey
version: '${project.version}'
main: me.shadowalzazel.mcodyssey.Odyssey
api-version: '1.20'
authors: [ShadowAlzazel]
description: A server side expansion pack for a new minecraft adventure!
