name: $name
main: me.shadowalzazel.mcodyssey.Odyssey
version: $version
api-version: $apiVersion
authors: [ShadowAlzazel]
description: $description

commands:
  summon_boss:
    description: "Summons an Odyssey boss."
    usage: /<command>
    permission: op
  summon_mob:
    description: "Summons a Custom Mob."
    usage: /<command>
    permission: op
  show_item:
    description: "Broadcasts the players held item."
    usage: /<command>
  ender_dragon_boss_battle:
    description: "Activates the hard ender dragon boss."
    usage: /<command>