name: MinecraftOdyssey
version: '${project.version}'
main: me.shadowalzazel.mcodyssey.MinecraftOdyssey
api-version: 1.19
authors: [ShadowAlzazel]
description: A server side expansion pack for a new minecraft adventure!

commands:
  SpawnAmbassador:
    description: ""
    usage: /<command>
    permission: op
  SpawnHogRider:
    description: ""
    usage: /<command>
    permission: op
  GiveTestItem:
    description: ""
    usage: /<command>
    permission: op
  SpawnTestMob:
    description: ""
    usage: /<command>
    permission: op
  SpawnTestKnight:
    description: ""
    usage: /<command>
    permission: op
  necronomicon:
    description: "Lol"
  TriggerPhenomenon:
    usage: /<command>
    permission: op